apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
  namespace: kube-system
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1alpha1
    kind: KubeSchedulerConfiguration
    schedulerName: scheduler-framework-sample
    leaderElection:
      leaderElect: true
      lockObjectName: scheduler-framework-sample
      lockObjectNamespace: kube-system
    plugins:
      queueSort:
        enabled:
        - name: Fit
        disabled:
        - name: "*"
      preFilter:
        enabled:
        - name: Fit
      filter:
        enabled:
        - name: Fit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-framework-sample
  namespace: kube-system
  labels:
    component: scheduler-framework-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      component: scheduler-framework-sample
  template:
    metadata:
      labels:
        component: scheduler-framework-sample
    spec:
      serviceAccount: sample-sa
      priorityClassName: system-cluster-critical
      volumes:
      - name: scheduler-config
        configMap:
          name: scheduler-config
      containers:
      - name: scheduler-ctrl
        image: index.docker.io/vincentpli/scheduler-framework-sample:v0.0.1
        imagePullPolicy: IfNotPresent
        args:
        - scheduler-framework-sample
        - --config=/scheduler/scheduler-config.yaml
        - --v=3
        resources:
          requests:
            cpu: "50m"
        volumeMounts:
        - name: scheduler-config
          mountPath: /scheduler